# Generated by Django 4.2.4 on 2023-08-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_model',
            fields=[
                ('u_id', models.IntegerField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=30)),
                ('u_email', models.EmailField(max_length=30)),
                ('u_address', models.TextField()),
                ('u_cont_number', models.CharField(max_length=11)),
                ('u_gender', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
