# Generated by Django 4.2.4 on 2023-08-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailorApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='measurementForShirt_model',
            fields=[
                ('s_productID', models.IntegerField(primary_key=True, serialize=False)),
                ('s_neck', models.IntegerField()),
                ('s_sleeve', models.IntegerField()),
                ('s_chest', models.IntegerField()),
                ('s_waist', models.IntegerField()),
                ('s_length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='payment_model',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_method', models.CharField(max_length=20)),
            ],
        ),
    ]
