# Generated by Django 4.2.4 on 2023-08-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailorApp', '0002_measurementforshirt_model_payment_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='design_model',
            fields=[
                ('d_id', models.IntegerField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='fabric_model',
            fields=[
                ('f_id', models.IntegerField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=30)),
                ('f_color', models.CharField(max_length=20)),
                ('f_type', models.CharField(max_length=30)),
                ('f_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='feedback_model',
            fields=[
                ('f_id', models.IntegerField(primary_key=True, serialize=False)),
                ('f_review', models.IntegerField()),
                ('f_comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='measureForSalwar_model',
            fields=[
                ('sl_hip', models.IntegerField(primary_key=True, serialize=False)),
                ('sl_len', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='measurementForKameez_model',
            fields=[
                ('k_productID', models.IntegerField(primary_key=True, serialize=False)),
                ('k_neckdep', models.IntegerField()),
                ('k_chest', models.IntegerField()),
                ('k_waist', models.IntegerField()),
                ('k_len', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='measurementForPant_model',
            fields=[
                ('pnt_len', models.IntegerField(primary_key=True, serialize=False)),
                ('pnt_waist', models.IntegerField()),
                ('pnt_inseam', models.IntegerField()),
                ('pnt_hsize', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='order_model',
            fields=[
                ('o_id', models.IntegerField(primary_key=True, serialize=False)),
                ('o_date', models.DateField()),
                ('o_type', models.CharField(max_length=30)),
                ('o_due', models.DateField()),
            ],
        ),
    ]
