# Generated by Django 4.2.4 on 2023-10-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailorApp', '0003_design_model_fabric_model_feedback_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabric_model',
            name='f_color',
        ),
        migrations.AddField(
            model_name='fabric_model',
            name='f_image',
            field=models.ImageField(default='', upload_to='fabric'),
        ),
    ]
