# Generated by Django 4.2.4 on 2023-10-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailorApp', '0004_remove_fabric_model_f_color_fabric_model_f_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='design_model',
            name='d_image',
            field=models.ImageField(default='', upload_to='TailorApp/design'),
        ),
        migrations.AlterField(
            model_name='fabric_model',
            name='f_image',
            field=models.ImageField(default='', upload_to='TailorApp/fabric'),
        ),
    ]
