# Generated by Django 4.2.6 on 2023-10-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TailorApp', '0005_design_model_d_image_alter_fabric_model_f_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_model',
        ),
    ]
