# Generated by Django 4.2.6 on 2023-10-14 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TailorApp', '0007_user_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fabric_model',
        ),
    ]
