# Generated by Django 4.2.6 on 2023-10-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailorApp', '0008_delete_fabric_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='fabric_model',
            fields=[
                ('f_id', models.IntegerField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=30)),
                ('f_type', models.CharField(max_length=30)),
                ('f_price', models.IntegerField()),
                ('f_image', models.ImageField(default='', upload_to='TailorApp/fabric')),
            ],
        ),
    ]
