# Generated by Django 4.2.6 on 2023-10-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailorApp', '0011_alter_design_model_d_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design_model',
            old_name='d_image',
            new_name='d_image1',
        ),
        migrations.AddField(
            model_name='design_model',
            name='d_image2',
            field=models.ImageField(default='', upload_to='design/images'),
        ),
        migrations.AddField(
            model_name='design_model',
            name='d_image3',
            field=models.ImageField(default='', upload_to='design/images'),
        ),
    ]
