# Generated by Django 4.2.6 on 2023-10-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailorApp', '0012_rename_d_image_design_model_d_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='design_kameez_model',
            fields=[
                ('dk_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dk_name', models.CharField(max_length=30)),
                ('dk_price', models.IntegerField()),
                ('dk_image1', models.ImageField(default='', upload_to='design/design_kameez/images')),
                ('dk_image2', models.ImageField(default='', upload_to='design/design_kameez/images')),
                ('dk_image3', models.ImageField(default='', upload_to='design/design_kameez/images')),
            ],
        ),
        migrations.CreateModel(
            name='design_salowaar_model',
            fields=[
                ('ds_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ds_name', models.CharField(max_length=30)),
                ('ds_price', models.IntegerField(max_length=30)),
                ('ds_image1', models.ImageField(default='', upload_to='design/images')),
                ('ds_image2', models.ImageField(default='', upload_to='design/images')),
            ],
        ),
        migrations.CreateModel(
            name='design_shirt_model',
            fields=[
                ('dsh_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dsh_name', models.CharField(max_length=30)),
                ('dsh_price', models.IntegerField()),
                ('dsh_image1', models.ImageField(default='', upload_to='design/design_kameez/images')),
                ('dsh_image2', models.ImageField(default='', upload_to='design/design_kameez/images')),
                ('dsh_image3', models.ImageField(default='', upload_to='design/design_kameez/images')),
            ],
        ),
        migrations.DeleteModel(
            name='design_model',
        ),
    ]
