# Generated by Django 4.2.6 on 2023-10-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailorApp', '0013_design_kameez_model_design_salowaar_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design_salowaar_model',
            name='ds_price',
            field=models.IntegerField(),
        ),
    ]
