# Generated by Django 4.2.6 on 2023-10-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailorApp', '0014_alter_design_salowaar_model_ds_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design_salowaar_model',
            name='ds_image2',
        ),
        migrations.RemoveField(
            model_name='design_shirt_model',
            name='dsh_image3',
        ),
        migrations.AddField(
            model_name='design_kameez_model',
            name='dk_neck',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='design_kameez_model',
            name='dk_sleeve',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='design_kameez_model',
            name='dk_type',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='design_shirt_model',
            name='dsh_hand',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='design_salowaar_model',
            name='ds_image1',
            field=models.ImageField(default='', upload_to='design/design_salowaar/images'),
        ),
        migrations.AlterField(
            model_name='design_shirt_model',
            name='dsh_image1',
            field=models.ImageField(default='', upload_to='design/design_shirt/images'),
        ),
        migrations.AlterField(
            model_name='design_shirt_model',
            name='dsh_image2',
            field=models.ImageField(default='', upload_to='design/design_/images'),
        ),
    ]
