# Generated by Django 4.2.6 on 2023-10-14 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TailorApp', '0017_measureforsalwar_model_measurementforkameez_model_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order_model',
        ),
    ]
