# Generated by Django 4.2.6 on 2023-10-14 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TailorApp', '0018_delete_order_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='shirt_order_model',
            fields=[
                ('o_id', models.IntegerField(primary_key=True, serialize=False)),
                ('o_date', models.DateField()),
                ('o_type', models.CharField(max_length=30)),
                ('o_due', models.DateField()),
                ('dsh_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TailorApp.design_shirt_model')),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TailorApp.fabric_model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='salowaar_order_model',
            fields=[
                ('o_id', models.IntegerField(primary_key=True, serialize=False)),
                ('o_date', models.DateField()),
                ('o_type', models.CharField(max_length=30)),
                ('o_due', models.DateField()),
                ('ds_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TailorApp.design_salowaar_model')),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TailorApp.fabric_model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='kameez_order_model',
            fields=[
                ('o_id', models.IntegerField(primary_key=True, serialize=False)),
                ('o_date', models.DateField()),
                ('o_type', models.CharField(max_length=30)),
                ('o_due', models.DateField()),
                ('dk_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TailorApp.design_kameez_model')),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TailorApp.fabric_model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
