# Generated by Django 4.2.6 on 2023-10-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailorApp', '0019_shirt_order_model_salowaar_order_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='type_model',
            fields=[
                ('ty_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ty_name', models.CharField(max_length=50)),
                ('ty_image', models.ImageField(default='', upload_to='types/images')),
            ],
        ),
    ]
