# Generated by Django 4.2.6 on 2023-10-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailorApp', '0021_measureforsalwar_model_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementforkameez_model',
            name='k_productID',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
