# Generated by Django 4.2.6 on 2023-10-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailorApp', '0024_remove_measureforsalwar_model_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measureforsalwar_model',
            name='sl_productID',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='measurementforshirt_model',
            name='s_productID',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
