# Generated by Django 4.2.6 on 2023-10-15 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TailorApp', '0025_alter_measureforsalwar_model_sl_productid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kameez_order_model',
            name='o_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kameez_order_model',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salowaar_order_model',
            name='o_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shirt_order_model',
            name='o_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
