# Generated by Django 4.2.6 on 2023-10-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailorApp', '0026_alter_kameez_order_model_o_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kameez_order_model',
            name='o_date',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='kameez_order_model',
            name='o_due',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='salowaar_order_model',
            name='o_date',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='salowaar_order_model',
            name='o_due',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='shirt_order_model',
            name='o_date',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='shirt_order_model',
            name='o_due',
            field=models.DateField(auto_created=True),
        ),
    ]
