# Generated by Django 5.0.6 on 2024-07-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TailorApp', '0029_remove_kameez_order_model_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_model',
            fields=[
                ('cont_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cont_name', models.CharField(max_length=50)),
                ('cont_email', models.EmailField(max_length=254)),
                ('cont_message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='feedback_model',
        ),
    ]
